
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/app_dev?&useTimezone=true&serverTimezone=UTC
    username: app_dev_user
    password: dwr
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
